### ISSUE TITLE
Permission to merge this branch into upstream

### ISSUE THREAD

**Issue by Quackster** [Sonykko/Havana_theallseeingeye#2]
Hello Sonykko,

I was wondering if I have permission to merge your work into [Quackster/Havana](https://github.com/Quackster/Havana).

You've done amazing work.

Full credits will be given to you where it is due of course. I will make amendments to the project where need be to ensure your work and contributions are recognised.  

I would do a pull request back into my repo but I see this repo isn't technically a fork, so I can't, and I'd need to download your source code to add it back into the upstream repository.

**Comment by Sonykko** [comment]
Hey Quackster!

First of all, thanks for the recognition, apreciate it. And thanks to bring me te inspiration of do this, because the day I saw your project and its documentation, I understood that it was the opportunity to create theallseeingeye.

And absolutly yes! You can merge my work into [Quackster/Havana](https://github.com/Quackster/Havana), but first and if you can, I would like to talk with you more about this (including fork, no fork, etc...) in Discord. And thank you for asking my permission, even if it is a project with a GNU license :)

And see my name inside Havana project as a contributor it's be an honor for me.

**Comment by SrEstarqui** [comment]
Awesome collaboration!
