### ISSUE TITLE
When I use this Havana-Web and Havana-Server then Public room The Park is not working

### ISSUE THREAD

**Issue by thebigvane** [Sonykko/Havana_theallseeingeye#3]
Only a black screen is shown.

**Comment by Sonykko** [comment]
Hey thebigvane!

That issue is solved in the latest Havana v1.1. For solve it, you need to download the latest theallseeingeye release (v2.1.7) that have been added last Havana v1.1 commits (and more) and download the latest DCR Pack updated by Quackster.

New DCR pack download link: [https://www.mediafire.com/file/914e36wg7m3oo3n/havana_www_2024_07_12.zip/file](https://www.mediafire.com/file/914e36wg7m3oo3n/havana_www_2024_07_12.zip/file)
theallseeingeye v2.1.7 download link: [https://github.com/Sonykko/Havana_theallseeingeye/releases](https://github.com/Sonykko/Havana_theallseeingeye/releases)

**Comment by thebigvane** [comment]
Thanks. It fixed the issue!

**Comment by Sonykko** [comment]
Perfect! U welcome!
